### ISSUE TITLE
Almost no commands in the dota2 folder work.

### ISSUE THREAD

**Issue by ivands** [DaMitchell/steam-api-php#11]
The most important requirement of a command is that it implements the CommandInterface.
None of your commands in the dota2 folder implement this interface.

Your tests run successfully because your not testing if the interface has been set. 
Plx fix this fast.
Would love to your use code when its tested and works.

**Comment by DaMitchell** [comment]
Thanks for pointing that out. I have added in the missing "implements" and added tests into to make sure all commands are implementing CommandInterface. 

If you see anything else please let me know or submit a PR. Thanks again.
