### ISSUE TITLE
Disable SSL certificate verification

### ISSUE THREAD

**Issue by faenir** [DaMitchell/steam-api-php#15]
How can I change [guzzle options](https://github.com/guzzle/guzzle/blob/443ca656dec18f3e5ea7751d2429fc2aeacf3ca2/docs/request-options.rst)? I need set [`SSL certificate verify`](https://github.com/guzzle/guzzle/blob/443ca656dec18f3e5ea7751d2429fc2aeacf3ca2/docs/request-options.rst#verify) to `false`.

**Comment by DaMitchell** [comment]
Sorry for taking sooooooo long to reply to this. 

If you take a look at this method in the Guzzle client [https://github.com/guzzle/guzzle/blob/master/src/Client.php#L158](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L158) you'll see you can set defaults.

So in your case you should be able to do something like:

```php
new GuzzleRunner(new Client(['verify' => false]), new GuzzleUrlBuilder())
```
Hope that will help. Again sorry for the really late reply.
